global:
  govcloud: true
  marketplace-ami: true
  owner: quickstart@amazon.com
  qsname: quickstart-trendmicro-deepsecurity
  regions:
    - us-east-1
  reporting: true
tests:
  defaults:
    parameter_input: defaults.json
    template_file: quickstart/trendmicro-deepsecurity-master.template
